# Generated by Django 5.1.5 on 2025-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.BigIntegerField()),
                ('accredation', models.TextField()),
                ('website', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('acceptance_rate', models.FloatField()),
                ('tution_fee', models.FloatField()),
                ('scholarship', models.BooleanField()),
                ('application_deadline', models.DateField()),
                ('entrance_exam_unive', models.BooleanField()),
                ('entrance_exams', models.TextField(blank=True, null=True)),
                ('mode_of_study', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('campus_size', models.CharField(max_length=255)),
                ('no_of_programs_offered', models.BigIntegerField()),
                ('intl_student_percentage', models.BigIntegerField()),
                ('campus_facilities', models.TextField()),
                ('ranking', models.BigIntegerField()),
            ],
        ),
    ]
